stage('docker-package'){
    agent any
    steps{
      echo 'Packaging worker app with docker'
      script{
        docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
            def workerImage = docker.build("xxxx/worker:v${env.BUILD_ID}", "./worker")
            workerImage.push()
            workerImage.push("latest")
        }
      }
    }
}